### PR TITLE
Use relative paths if `--tag-relative=yes`

### PR DESCRIPTION
**Pull request by fedragon**
This addresses https://github.com/ceedubs/sbt-ctags/issues/13.
It makes it possible to generate relative paths, to solve the Atom integration issue... if you agree with my changes, please release asap :)

### CODE REVIEW

**Comment by ceedubs** [comment]
Thanks for submitting this, @fedragon!

I'm not sure about this approach. Doing string parsing ([here](https://github.com/ceedubs/sbt-ctags/pull/14/files#diff-6ad8e7f46c145ae2a6e119c006408596R59)) on the ctags command seems like a brittle approach to determining whether or not to use relative paths. For example, `tag-relative` defaults to `yes` if the user is using the `e` option, so we would be doing the wrong thing if they were using `-e` with its defaults.

I think that even if it's a bit more verbose, it would be good to use an explicit setting for whether or not to use relative paths.

**Comment by fedragon** [comment]
Hello @ceedubs, thanks for the feedback! I agree with your remarks, the previous implementation was a bit naive... I just pushed another commit to the same branch, please let me know what you think about it!

**Comment by fedragon** [comment]
Uhm I actually think that these changes I pushed are still not ideal: I think that I should also check if a `~/.ctags` file exists and, if so, load all the options in it (`--recurse`, `--tag-relative` and so on) into `CtagsParams` to keep the behaviour of the plugin consistent. I'll look into it!

**Comment by fedragon** [comment]
@ceedubs I deleted my previous comment because I realized that the plugin only reads `lang` options from `tags` files: I think my changes should address your feedback!

**Comment by ceedubs** [comment]
@fedragon thanks a bunch for this! Sorry that I was so slow in responding/merging. It looks good to me. :+1:

Reading through #13, it seems like maybe relative paths should be the default? It sounds like some editors don't accept relative paths. I wonder if there are any that don't accept relative paths? cc @raboof.

**Comment by fedragon** [comment]
@ceedubs could you maybe release a new version including these changes?

**Pull request merged**
