### PR TITLE
Generate ctags also for scala/java test directories

### PR DESCRIPTION
**Pull request by fedragon**
Hello,
thank you for this plugin!
Personally I find useful to also create ctags for scala/java test directories, so here we are :)

### CODE REVIEW

**Comment by ceedubs** [comment]
@fedragon thanks a lot for the pull request! Sorry for my delay in getting to it.

I have a couple questions:
* I can see that the `scalaVersion` was outdated and you removed it. What is the implication of a `scalaVersion` not being present? Will it default to the latest release or something? Will this break anything for people who are using Scala 2.10.x? (Sorry I don't actually know anything about SBT - I have no idea how I managed to get this plugin kind of working)
* What's the reasoning for targeting 1.7? Is that needed for this change for some reason?

Thanks!

**Comment by fedragon** [comment]
@ceedubs I removed the Scala version by mistake while compiling, sorry! I just restored it and bumped it to 2.10.4 (latest 2.10 stable). 
It's been a while so I cannot recall exactly why I decided to target 1.7, I guess I did it so that users of this library are not required to have Java 8... I can revert this change if you prefer, just let me know!

**Comment by ceedubs** [comment]
Thanks for the clarification and quick turnaround, @fedragon.

If you can't recall why you targeted 1.7, that would be great if you could go ahead and undo that bit as well. I don't think users are otherwise required to have Java 8; I'm pretty sure I don't have it installed. Let me know if you run into issues without it, though.

**Comment by fedragon** [comment]
does not seem to create any issue, removed it

**Comment by ceedubs** [comment]
Seems to work locally for me, and this is something I meant to add a long time ago but forgot to do. Thanks, @fedragon!

**Comment by fedragon** [comment]
Hello, could you maybe create a new release to bring these changes in? :)

**Comment by ceedubs** [comment]
Wow sorry for that super-long delay. I've just published 0.2.0.

**Comment by fedragon** [comment]
Thanks!

**Pull request merged**
